### ISSUE TITLE
Build Failure in 3.0.rc17

### ISSUE THREAD

**Issue by ejgallego** [kmatheussen/radium#252]
Hi,

thanks for making radium open source, I'm looking forward to try it!

I tried to build on linux (Ubuntu 14.10) and I got an almost full build, but I'm stuck at:

```shell
make[1]: Entering directory '/home/egallego/tmp/radium-3.0.rc17/pluginhost/Builds/Linux'
Compiling Juce_plugins.cpp
cd Qt/ && ./create_source_from_ui.sh uic moc pd_plugin_widget
g++ -mfpmath=sse -msse2 Qt/Qt_instruments.cpp -c `cat buildtype.opt` -Ibin/packages/gc-7.2/include -IQt/ -I/usr/include/python2.7 -DNOPAUSEPLAY -DCOMPILING_RADIUM -DGUIISQT -DUSE_GFX_OP_QUEUE -DFULL_VERSION=1 -DIS_LITTLE_ENDIAN=1 -DUSE_OPENGL=1 -DUSE_QT_VISUAL=1 -DUSE_GTK_VISUAL=0 -DUSE_QT_REQTYPE=1 -DUSE_GTK_REQTYPE=0 -DUSE_QT_MENU=1 -DUSE_GTK_MENU=0 -Imidi/rtmidi -Werror=array-bounds -msse2 -DFOR_LINUX -DWITH_PD  -Wno-unused-function -DUSE_VESTIGE=1 -Wno-unused-function -DUSE_QT4 -DUSE_QIMAGE_BUFFER=1 `pkg-config --cflags Qt3Support --cflags QtOpenGL` -Ibin/packages/qhttpserver-master/src -DQHTTPSERVER_EXPORT  
Compiling juce_audio_basics.cpp
Compiling juce_audio_processors.cpp
In file included from ../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.cpp:151:0:
../../JuceLibraryCode/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:49:44: fatal error: pluginterfaces/vst2.x/aeffectx.h: No such file or directory
 #include "pluginterfaces/vst2.x/aeffectx.h"
                                            ^
compilation terminated.
Makefile:92: recipe for target 'build/intermediate/Release/juce_audio_processors_44a134a2.o' failed
make[1]: *** [build/intermediate/Release/juce_audio_processors_44a134a2.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/egallego/tmp/radium-3.0.rc17/pluginhost/Builds/Linux'
Makefile:412: recipe for target 'pluginhost/Builds/Linux/build/libMyPluginHost.a' failed
make: *** [pluginhost/Builds/Linux/build/libMyPluginHost.a] Error 2
make: *** Waiting for unfinished jobs....
```

Best,
E.

**Comment by kmatheussen** [comment]
I've forgotten to update the README file. You need the steinberg headers: 
http://www.steinberg.net/en/company/developers.html

**Comment by ejgallego** [comment]
Cool thanks very much! Compilation was good!
