### ISSUE TITLE
latest radium with qt 5.9.5 QMetaobject::invokeMethod class error

### ISSUE THREAD

**Issue by GeorgeNs** [kmatheussen/radium#1225]
Hi guys,long time no see :)
I m wondering why getting this error trying to build with qt5.9.5,make packages runs smoothly
thnxxxx

Qt/Qt_progresswindow.cpp: In member function ‘virtual void {anonymous}::ReadStdinThread::run()’:
Qt/Qt_progresswindow.cpp:435:35: error: no matching function for call to ‘QMetaObject::invokeMethod(QApplication*, {anonymous}::ReadStdinThread::run()::<lambda()>)’
                                   );
                                   ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:46:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication:1,
                 from Qt/Qt_progresswindow.cpp:5:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:406:17: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)

**Comment by kmatheussen** [comment]
Seems like this method was introduced in qt 5.10:
https://doc.qt.io/qt-5/qmetaobject.html#invokeMethod-4
So your version of qt is too old.

**Comment by GeorgeNs** [comment]
thanks for the info.
for now radium 5.9.41 is the last version  before introducing that new class and it works.
unfortunately updating the qt is not an option right now

**Comment by kmatheussen** [comment]
Doesn't seem to be a fairly simple to use alternative to that method, so I've changed the build system to require Qt 5.10 or newer.

**Comment by GeorgeNs** [comment]
Alright. 5.9.41 version is fine for having tests and fun.
But what if i just replace the new method with the new one. It seems not a big deal should work i guess.
any red flags?

**Comment by kmatheussen** [comment]
Not sure what you mean. But you can probably just comment out that call.
The progresswindow will stop working though.

**Comment by GeorgeNs** [comment]
I mean to replace all these private members until #endif line 488 with the old ones

**Comment by kmatheussen** [comment]
What is the "old ones"?

**Comment by GeorgeNs** [comment]
the old ones i mean the private members from radium 5.9.41

**Comment by kmatheussen** [comment]
Oh, yeah you could try something like that, but it probably won't compile,
or be stable. If it doesn't work, just comment out the call to
QMetaobject::invokeMethod.

**Comment by GeorgeNs** [comment]
yeah it seems works!
