### ISSUE TITLE
QDesktopWidget::availableGeometry() is deprecated (Qt >=5.11)

### ISSUE THREAD

**Issue by Teteros** [kmatheussen/radium#1226]
Compiling radium 5.9.71, this blocks compile on Qt 5.13.0:

On clang8
```
In file included from Qt/Qt_Error.cpp:13:
Qt/helpers.h:152:45: error: 'availableGeometry' is deprecated: Use QGuiApplication::screens() [-Werror,-Wdeprecated-declarations]
      parentRect = QApplication::desktop()->availableGeometry();
                                            ^
/usr/include/qt/QtWidgets/qdesktopwidget.h:88:5: note: 'availableGeometry' has been explicitly marked deprecated here
    QT_DEPRECATED_X("Use QGuiApplication::screens()") const QRect availableGeometry(int screen = -1) const;
    ^
/usr/include/qt/QtCore/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/usr/include/qt/QtCore/qcompilerdetection.h:649:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
1 error generated.
make: *** [Makefile:1659: bin/radium_error_message] Error 1
```

gcc9
```
In file included from Qt/Qt_Error.cpp:13:
Qt/helpers.h: In function ‘QPoint getCentrePosition(QWidget*, int, int, QRect)’:
Qt/helpers.h:152:63: error: ‘const QRect QDesktopWidget::availableGeometry(int) const’ is deprecated: Use QGuiApplication::screens() [-Werror=deprecated-declarations]
  152 |       parentRect = QApplication::desktop()->availableGeometry();
      |                                                               ^
In file included from /usr/include/qt/QtWidgets/QDesktopWidget:1,
                 from Qt/helpers.h:14,
                 from Qt/Qt_Error.cpp:13:
```

Seems `availableGeometry()` is deprecated since Qt 5.11:
https://doc.qt.io/archives/qt-5.11/qdesktopwidget-obsolete.html
https://bugreports.qt.io/browse/QTBUG-68785

**Comment by Teteros** [comment]
Anyone else building radium 5.9.71 getting this, you can suppress the errors with `-Wno-deprecated-declarations` (already used in some parts of Makefile.Qt upstream)

e.g: `patch -p1 < suppress-qt-deprecation-errors.patch`
```diff
diff -aur --no-dereference radium-5.9.71.pristine/Makefile.Qt radium-5.9.71.new/Makefile.Qt
--- radium-5.9.71.pristine/Makefile.Qt	2019-07-13 10:45:22.009924291 +0100
+++ radium-5.9.71.new/Makefile.Qt	2019-07-13 10:41:32.489932129 +0100
@@ -1452,7 +1452,7 @@
 	$(MOC) $(P)Qt_PopupMenu.cpp -DUSE_QT_MENU >$(P)mQt_PopupMenu.cpp
 
 Qt_MainWindow.o:  $(BUILD_DEPENDENCIES) $(P)Qt_MainWindow.cpp $(P)mQt_bottom_bar_widget_callbacks.h $(P)mQt_upperleft_widget_callbacks.h $(P)Rational.h $(P)lzqlineedit.h $(P)helpers.h audio/CpuUsage.hpp Qt/EditorWidget.h  Qt/FileRequester.hpp
-	$(CCC) $(P)Qt_MainWindow.cpp $(QTOPT)
+	$(CCC) $(P)Qt_MainWindow.cpp $(QTOPT) -Wno-deprecated-declarations
 
 Qt_Time.o:  $(BUILD_DEPENDENCIES) $(P)Qt_Time.cpp
 	$(CCC) $(P)Qt_Time.cpp $(QTOPT)
@@ -1656,7 +1656,7 @@
 	@echo "Changed (bin/radium_error_message):"
 	@echo $?
 	@echo
-	$(CCC) -Wall -Werror $(P)Qt_Error.cpp $(CPPOPT) $(QT_CFLAGS) $(OS_OPTS) -DCOMPILE_EXECUTABLE $(QT_GUI_CFLAGS) -o errormessagebin.o -Wno-missing-declarations
+	$(CCC) -Wall -Werror $(P)Qt_Error.cpp $(CPPOPT) $(QT_CFLAGS) $(OS_OPTS) -DCOMPILE_EXECUTABLE $(QT_GUI_CFLAGS) -o errormessagebin.o -Wno-missing-declarations -Wno-deprecated-declarations
 	$(LINKER) `cat buildtype.opt` errormessagebin.o -o bin/radium_error_message $(QT_GUI_LDFLAGS)
 	rm errormessagebin.o
 
diff -aur --no-dereference radium-5.9.71.pristine/pluginhost/Builds/Linux/Makefile radium-5.9.71.new/pluginhost/Builds/Linux/Makefile
--- radium-5.9.71.pristine/pluginhost/Builds/Linux/Makefile	2019-07-13 10:45:22.009924291 +0100
+++ radium-5.9.71.new/pluginhost/Builds/Linux/Makefile	2019-07-13 10:40:51.449933531 +0100
@@ -99,7 +99,7 @@
 $(OBJDIR)/Juce_plugins_6c083ccb.o: ../../../audio/Juce_plugins.cpp
 	-@mkdir -p $(OBJDIR)
 	@echo "Compiling Juce_plugins.cpp"
-	$(CXX) $(CXXFLAGS) -Wall -o "$@" -c "$<"
+	$(CXX) $(CXXFLAGS) -Wall -o "$@" -c "$<" -Wno-deprecated-declarations
 
 $(OBJDIR)/Juce_plugin_scanner.o: ../../../audio/Juce_plugin_scanner.cpp
 	-@mkdir -p $(OBJDIR)
```
