### ISSUE TITLE
problem compiling with linker

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [kmatheussen/radium#1397]
I get these errors when trying to compile:

undefined reference to `ZSTD_compress' 
error adding symbols: DSO missing from command line

Last version i managed to compile was 7.1.68.

Using updated arch linux with the AUR PKGBUILD.

I have zstd installed of course.

**Comment by yust1n** [comment]
same error occurs on slackware 15.0 using binutils 2.40
compiling works fine on artix with binutils 2.39-2

**Comment by yust1n** [comment]
https://aur.archlinux.org/packages/radium7
found the problem and patched it

**Comment by kmatheussen** [comment]
So there's nothing to fix in Radium? Then i'll just close the issue.

**Comment by yust1n** [comment]
Here is the diff :
https://aur.archlinux.org/cgit/aur.git/tree/build_linux_common.patch?h=radium

**Comment by kmatheussen** [comment]
Thank you. I'm not applying upstream, since it's not necessary on other distros as far as I know, but it's good to know that there is a fix for the problem.
